config/routes.rb
SampleApp::Application.routes.draw do

  devise_for :users,
             :path => '',
             :path_names => {:sign_in => 'sign-in',
                             :sign_out => 'sign-out',
                             :registration => 'account',
                             :edit => 'edit' },
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                               :registrations => "users/registrations" }

  root 'static#home'

  get '/account', to: 'users#show', as: 'account'

  resources :reviews, only: [:new, :create, :update, :show, :edit, :destroy]
  resources :users, only: [:show, :index]

  

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include ApplicationHelper

  before_filter :ensure_signed_in,
                :only => [:destroy, :new, :create, :update, :edit]

  skip_before_filter :verify_authenticity_token

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id

    # if the review isn't valid don't do any existing address lookup
    if !@review.valid?
      render 'new'
      return
    end

    merge_in_existing_address @review

    if @review.save
      flash[:success] = "Awesome! Thanks for adding a review."
      redirect_to @review
    else
      render 'new'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    raise SecurityTransgression unless @review.is_owner?(current_user)

    @review.destroy

    redirect_to current_user
  end

  def edit
    @review = Review.find(params[:id])
    raise SecurityTransgression unless @review.is_owner?(current_user)
  end

  def new
    @review = Review.new
    @review.address = Address.new
  end

  def show
    @review = Review.find(params[:id])
  end

  def update
    sanitized_params = review_params
    @review = Review.find(params[:id])
    raise SecurityTransgression unless @review.is_owner?(current_user)

    address_changed = will_address_change(@review.address, sanitized_params[:address_attributes])
    sanitized_params.except!(:address_attributes) if !address_changed

    @review.assign_attributes(sanitized_params)

    # if the review isn't valid don't do any existing address lookup
    if !@review.valid?
      render 'edit'
      return
    end

    address_id_before_merge = @review.address_id
    merge_in_existing_address @review

    # if an address is changed create a new record instead of updating it
    if @review.address_id == address_id_before_merge && address_changed
      @review.address = @review.address.dup
    end

    if @review.save
      redirect_to review_path(@review)
    else
      render 'edit'
    end
  end

  private
  def review_params
    params.require(:review).permit(:user_id, :address_id, :start_date, :end_date, :building_rating, :furnishings_rating, :noise_rating, :amenities_rating, :transport_rating,
                                   :building_comments, :furnishings_comments, :noise_comments, :amenities_comments, :transport_comments,
                                   :address_attributes => [:id, :flat_number, :street_number, :route, :postal_town, :postal_code, :country, :decimal_degrees_latitude, :decimal_degrees_longitude])
  end

  def will_address_change(addressRecord, addressParams)
    addressRecord.flat_number != addressParams[:flat_number] ||
        addressRecord.street_number != addressParams[:street_number] ||
        addressRecord.route != addressParams[:route] ||
        addressRecord.postal_code != addressParams[:postal_code] ||
        addressRecord.postal_town != addressParams[:postal_town] ||
        addressRecord.country != addressParams[:country] ||
        addressRecord.decimal_degrees_latitude != addressParams[:decimal_degrees_latitude] ||
        addressRecord.decimal_degrees_longitude != addressParams[:decimal_degrees_longitude]
  end

  # replace the address on the review with an existing record if we have one
  def merge_in_existing_address(review)
    existing_address = Address.find_by postal_code: review.address.postal_code,
                                        route: review.address.route,
                                        street_number: review.address.street_number,
                                        flat_number: review.address.flat_number

    review.address = existing_address if existing_address
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_javascript.html.erb
<script>
    var autocomplete;

    $(document).ready(function () {
        $('[data-behavior~=datepicker]').datepicker({
            startView: 2,
            todayBtn: "linked",
            autoclose: true,
            format: "dd/mm/yyyy"
        });

        // focus address search if not been used yet
        if ($('#address-search').val() == '') {
            $("#address-search").focus();
        }

        $('#review_building_rating').slider();
        $('#review_furnishings_rating').slider();
        $('#review_noise_rating').slider();
        $('#review_amenities_rating').slider();
        $('#review_transport_rating').slider();

        // create the autocomplete object, restricting the search to addresses
        autocomplete = new google.maps.places.Autocomplete(
                /** @type {HTMLInputElement} */(document.getElementById('address-search')),
                { types: ['geocode'] });
        google.maps.event.addListener(autocomplete, 'place_changed', function () {
            fillInAddress();
        });

        // prevent enter key from submitting the form when choosing an address via autocomplete
        $('#address-search').keypress(function (event) {
            return event.keyCode != 13;
        });

        // disable or enable address fields depending on whether auto complete location has been picked
        <% if (@review.address.decimal_degrees_latitude.blank?) %>
            //enableAddressControls(false);
        <% else %>
            //enableAddressControls(true);
        <% end %>

        // show map and zoom to location if already present
        <% if (!@review.address.decimal_degrees_latitude.blank?) %>
            var location = new google.maps.LatLng(<%= @review.address.decimal_degrees_latitude %>, <%= @review.address.decimal_degrees_longitude %>);
            showMap(location, false);
        <% end %>
    })

    function enableAddressControls(enabled) {
        $('#review_address_attributes_flat_number').attr('disabled', !enabled);
        $('#review_address_attributes_street_number').attr('disabled', !enabled);
        $('#review_address_attributes_route').attr('disabled', !enabled);
        $('#review_address_attributes_postal_town').attr('disabled', !enabled);
        $('#review_address_attributes_postal_code').attr('disabled', !enabled);
        $('#form-group-map').toggle(enabled);
    }

    function geolocate() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                var geolocation = new google.maps.LatLng(
                        position.coords.latitude, position.coords.longitude);
                autocomplete.setBounds(new google.maps.LatLngBounds(geolocation,
                        geolocation));
            });
        }
    }

    function fillInAddress() {
        // Get the place details from the autocomplete object.
        var place = autocomplete.getPlace();

        // clear existing values
        document.getElementById('review_address_attributes_flat_number').value = "";
        document.getElementById('review_address_attributes_street_number').value = "";
        document.getElementById('review_address_attributes_route').value = "";
        document.getElementById('review_address_attributes_postal_town').value = "";
        document.getElementById('review_address_attributes_postal_code').value = "";

        // enable form controls
        enableAddressControls(true);

        // fill in hidden longitude and latitude
        setLatitude(place.geometry.location.lat());
        setLongitude(place.geometry.location.lng());

        for (var i = 0; i < place.address_components.length; i++) {
            var addressType = place.address_components[i].types[0];
            var addressLongName = place.address_components[i]['long_name'];

            // street_number
            if (addressType == 'street_number' && addressLongName) {
                document.getElementById('review_address_attributes_street_number').value = addressLongName;
            }

            // street
            if (addressType == 'route' && addressLongName) {
                document.getElementById('review_address_attributes_route').value = addressLongName;
            }

            // town
            if ($.inArray(addressType, ['postal_town', 'locality']) > -1 && addressLongName) {
                document.getElementById('review_address_attributes_postal_town').value = addressLongName;
            }

            // postal_code
            if ($.inArray(addressType, ['postal_code', 'postal_code_prefix']) > -1 && addressLongName) {
                document.getElementById('review_address_attributes_postal_code').value = addressLongName;
            }

            // postal_code
            if (addressType == 'route' && addressLongName) {
                document.getElementById('review_address_attributes_country').value = addressLongName;
            }

            var div = document.getElementById('address');
            div.innerHTML = div.innerHTML + '<br /> Type:' + addressType + '. Short: ' + place.address_components[i]['short_name'] + '. Long: ' + place.address_components[i]['long_name'];
        }

        showMap(place.geometry.location, true);
    }

    function showMap(location, animate) {
        // center map on location
        var mapOptions = {
            zoom: 18,
            center: location,
            streetViewControl: false,
            scrollwheel: false,
            mapTypeId: google.maps.MapTypeId.HYBRID
        };

        map = new google.maps.Map(document.getElementById('map-canvas'),
                mapOptions);

        // add the draggable marker
        var marker = new google.maps.Marker({
            draggable: true,
            position: location,
            animation: animate ? google.maps.Animation.DROP: null,
            map: map,
            title: "Where you lived."
        });

        // update update hidden lng and lat fields whenever the marker is dragged
        google.maps.event.addListener(marker, 'dragend', function (event) {
            setLatitude(this.getPosition().lat());
            setLongitude(this.getPosition().lng());
        });

        // show the map div
        $('#map-container').show()
    }

    function setLatitude(latitude) {
        document.getElementById('review_address_attributes_decimal_degrees_latitude').value = latitude
    }

    function setLongitude(longitude) {
        document.getElementById('review_address_attributes_decimal_degrees_longitude').value = longitude
    }

</script>

app/views/reviews/_review_form.html.erb
<%= form_for @review, html: {class: 'form-horizontal'} do |f| %>

    <%= render 'shared/error_messages', record: @review %>

    <fieldset>
      <legend>Where did you live?</legend>
      <div class='form-group'>
        <label class="sr-only" for="search">Search for an address</label>

        <div class='col-sm-8 col-sm-offset-2'>
          <%= text_field_tag :search, params[:search], {:id => 'address-search', :class => 'form-control input-lg', :placeholder => 'Search for an address or street name', :onFocus => 'geolocate()'} %>
          <span class='help-block'>The search isn't perfect, <strong>please try without the flat or house number
            if you have any problems</strong>.</span>
        </div>
      </div>

      <%= f.fields_for :address do |af| %>

          <%= af.hidden_field :decimal_degrees_latitude %>
          <%= af.hidden_field :decimal_degrees_longitude %>
          <%= af.hidden_field :country %>

          <div class='form-group'>
            <%= af.label :flat_number, class: "col-sm-2 control-label" %>

            <div class='col-sm-4'>
              <%= af.text_field :flat_number, class: 'form-control' %>
            </div>
          </div>

          <div class='form-group'>
            <%= af.label :street_number, class: "col-sm-2 control-label" %>

            <div class='col-sm-4'>
              <%= af.text_field :street_number, class: 'form-control' %>
            </div>
          </div>

          <div class='form-group'>
            <%= af.label :route, class: "col-sm-2 control-label" %>

            <div class='col-sm-6'>
              <%= af.text_field :route, class: 'form-control' %>
            </div>
          </div>

          <div class='form-group'>
            <%= af.label :postal_town, class: "col-sm-2 control-label" %>

            <div class='col-sm-6'>
              <%= af.text_field :postal_town, class: 'form-control' %>
            </div>
          </div>

          <div class='form-group'>
            <%= af.label :postal_code, class: "col-sm-2 control-label" %>

            <div class='col-sm-6'>
              <%= af.text_field :postal_code, class: 'form-control' %>
            </div>
          </div>

          <div class='form-group' id='form-group-map'>
            <label class='col-sm-2 control-label' for="map">Exact Location</label>

            <div class='col-sm-6'>
              <span class='help-block'>Help us get just the right place, drag the marker on the map below to where you lived.</span>

              <div id="map-canvas"></div>
            </div>
          </div>

      <% end %>

    </fieldset>


    <fieldset>
      <legend>When did you live there?</legend>

      <div class='form-group'>
        <%= f.label :start_date, "Moved In", class: "col-sm-2 control-label" %>

        <div class='col-sm-3 input-group'>
          <%= f.text_field :start_date, class: 'form-control', data: {behavior: "datepicker"} %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label :end_date, "Moved Out", class: "col-sm-2 control-label" %>

        <div class='col-sm-3 input-group'>
          <%= f.text_field :end_date, class: 'form-control', :placeholder => 'I still live there...', data: {behavior: "datepicker"} %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>What was it like?</legend>
      <p>Rate the below aspects of the property from 0 to 10 and add any comments you think will be useful.</p>
      <p>Try to include details which would be difficult to know about from a viewing.</p>

      <div class='form-group'>
        <%= f.label :building_rating, class: "col-sm-2 control-label" %>

        <div class='col-sm-8'>
          <%= f.text_field :building_rating, class: 'form-control', data: {:'slider-min' => "1", :'slider-max' => "10", :'slider-step' => "1", :'slider-value' => @review.building_rating ||= "5"} %>
          <span class='help-block'>What is the building like? Think about the entryways, security, lifts and stairways, parking. Any problems with damp or cracks in the walls?</span>
        </div>

        <%= f.label :building_comments, class: "sr-only" %>

        <div class='col-sm-8 col-sm-offset-2'>
          <!-- , placeholder: 'Neat gated entryway on traditional Georgian street. Takes a long time to heat up. No obvious structural damage or damp. The on street parking is often crowded.' -->
          <%= f.text_area :building_comments, class: 'form-control', height: 5 %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :furnishings_rating, class: "col-sm-2 control-label" %>

        <div class='col-sm-8'>
          <%= f.text_field :furnishings_rating, class: 'form-control', data: {:'slider-min' => "1", :'slider-max' => "10", :'slider-step' => "1", :'slider-value' => @review.furnishings_rating ||= "5"} %>
          <span class='help-block'>Think about the furniture, fittings, and finishings. Are the kitchen units nice? Do all the windows work? Are there enough power sockets?</span>
        </div>

        <%= f.label :furnishings_comments, class: "sr-only" %>

        <div class='col-sm-8 col-sm-offset-2'>
          <%= f.text_area :furnishings_comments, class: 'form-control' %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :noise_rating, class: "col-sm-2 control-label" %>

        <div class='col-sm-8'>
          <%= f.text_field :noise_rating, class: 'form-control', data: {:'slider-min' => "1", :'slider-max' => "10", :'slider-step' => "1", :'slider-value' => @review.noise_rating ||= "5"} %>
          <span class='help-block'>Can you hear passing trains, traffic or the nearby school playground? How well insulated are you from the neighbours?</span>
        </div>

        <%= f.label :noise_comments, class: "sr-only" %>

        <div class='col-sm-8 col-sm-offset-2'>
          <%= f.text_area :noise_comments, class: 'form-control' %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :amenities_rating, class: "col-sm-2 control-label" %>

        <div class='col-sm-8'>
          <%= f.text_field :amenities_rating, class: 'form-control', data: {:'slider-min' => "1", :'slider-max' => "10", :'slider-step' => "1", :'slider-value' => @review.amenities_rating ||= "5"} %>
          <span class='help-block'>Are there any good supermarkets, parks, coffee shops, gyms, launderettes, etc. nearby?</span>
        </div>

        <%= f.label :amenities_comments, class: "sr-only" %>

        <div class='col-sm-8 col-sm-offset-2'>
          <%= f.text_area :amenities_comments, class: 'form-control' %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :transport_rating, class: "col-sm-2 control-label" %>

        <div class='col-sm-8'>
          <%= f.text_field :transport_rating, class: 'form-control', data: {:'slider-min' => "1", :'slider-max' => "10", :'slider-step' => "1", :'slider-value' => @review.transport_rating ||= "5"} %>
          <span class='help-block'>Are there nearby rail and bus services? Is there good bicycle access to the property?</span>
        </div>

        <%= f.label :transport_comments, class: "sr-only" %>

        <div class='col-sm-8 col-sm-offset-2'>
          <%= f.text_area :transport_comments, class: 'form-control' %>
        </div>
      </div>
    </fieldset>

    <hr/>
    <%= button_tag "Save Review", :name => 'save', :class => 'btn btn-primary btn-xl col-sm-offset-2' %>
    <%= link_to 'Cancel', @review, :class => 'btn btn-warning btn-xl' if action_name == 'edit' %>

<% end %>

app/views/reviews/_review_js.html.erb
<script>
    var autocomplete;

    $(document).ready(function () {
        $('[data-behavior~=datepicker]').datepicker({
            startView: 2,
            todayBtn: "linked",
            autoclose: true,
            format: "dd/mm/yyyy"
        });

        // focus address search if not been used yet
        if ($('#address-search').val() == '') {
            $("#address-search").focus();
        }

        $('#review_building_rating').slider();
        $('#review_furnishings_rating').slider();
        $('#review_noise_rating').slider();
        $('#review_amenities_rating').slider();
        $('#review_transport_rating').slider();

        // create the autocomplete object, restricting the search to addresses
        autocomplete = new google.maps.places.Autocomplete(
                /** @type {HTMLInputElement} */(document.getElementById('address-search')),
                { types: ['geocode'] });
        google.maps.event.addListener(autocomplete, 'place_changed', function () {
            fillInAddress();
        });

        // prevent enter key from submitting the form when choosing an address via autocomplete
        $('#address-search').keypress(function (event) {
            return event.keyCode != 13;
        });

        // disable or enable address fields and map depending on whether auto complete location has been picked
        toggleAddressControls(false);
        toggleMap(<%= !@review.address.decimal_degrees_latitude.blank? %>);
    })

    function toggleAddressControls(enabled) {
        $('#review_address_attributes_flat_number').attr('disabled', !enabled);
        $('#review_address_attributes_street_number').attr('disabled', !enabled);
        $('#review_address_attributes_route').attr('disabled', !enabled);
        $('#review_address_attributes_postal_town').attr('disabled', !enabled);
        $('#review_address_attributes_postal_code').attr('disabled', !enabled);
    }

    function toggleMap(enabled) {
        $('#form-group-map').toggle(enabled);

        if (enabled) {
            <% if !@review.address.decimal_degrees_latitude.blank? %>
            var location = new google.maps.LatLng(<%= @review.address.decimal_degrees_latitude %>, <%= @review.address.decimal_degrees_longitude %>);
            showMap(location, false);
            <% end %>
        }
    }

    function geolocate() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                var geolocation = new google.maps.LatLng(
                        position.coords.latitude, position.coords.longitude);
                autocomplete.setBounds(new google.maps.LatLngBounds(geolocation,
                        geolocation));
            });
        }
    }

    function fillInAddress() {
        var place = autocomplete.getPlace();

        // clear existing values
        document.getElementById('review_address_attributes_flat_number').value = "";
        document.getElementById('review_address_attributes_street_number').value = "";
        document.getElementById('review_address_attributes_route').value = "";
        document.getElementById('review_address_attributes_postal_town').value = "";
        document.getElementById('review_address_attributes_postal_code').value = "";

        toggleAddressControls(true);
        toggleMap(true);

        setLatitude(place.geometry.location.lat());
        setLongitude(place.geometry.location.lng());

        for (var i = 0; i < place.address_components.length; i++) {
            var addressType = place.address_components[i].types[0];
            var addressLongName = place.address_components[i]['long_name'];

            // street_number
            if (addressType == 'street_number' && addressLongName) {
                document.getElementById('review_address_attributes_street_number').value = addressLongName;
            }

            // street
            if (addressType == 'route' && addressLongName) {
                document.getElementById('review_address_attributes_route').value = addressLongName;
            }

            // town
            if ($.inArray(addressType, ['postal_town', 'locality']) > -1 && addressLongName) {
                document.getElementById('review_address_attributes_postal_town').value = addressLongName;
            }

            // postal_code
            if ($.inArray(addressType, ['postal_code', 'postal_code_prefix']) > -1 && addressLongName) {
                document.getElementById('review_address_attributes_postal_code').value = addressLongName;
            }

            // country
            if (addressType == 'country' && addressLongName) {
                document.getElementById('review_address_attributes_country').value = addressLongName;
            }
        }

        showMap(place.geometry.location, true);
    }

    function showMap(location, animate) {
        // center map on location
        var mapOptions = {
            zoom: 18,
            center: location,
            streetViewControl: false,
            scrollwheel: false,
            mapTypeId: google.maps.MapTypeId.HYBRID
        };

        map = new google.maps.Map(document.getElementById('map-canvas'),
                mapOptions);

        // add the draggable marker
        var marker = new google.maps.Marker({
            draggable: true,
            position: location,
            animation: animate ? google.maps.Animation.DROP : null,
            map: map,
            title: "Where you lived."
        });

        // update update hidden lng and lat fields whenever the marker is dragged
        google.maps.event.addListener(marker, 'dragend', function (event) {
            setLatitude(this.getPosition().lat());
            setLongitude(this.getPosition().lng());
        });

        // show the map div
        $('#map-container').show()
    }

    function setLatitude(latitude) {
        document.getElementById('review_address_attributes_decimal_degrees_latitude').value = latitude
    }

    function setLongitude(longitude) {
        document.getElementById('review_address_attributes_decimal_degrees_longitude').value = longitude
    }
</script>

app/views/reviews/_review_preview_score.html.erb
<li>
  <span class="category heat<%= score %>"><%= category %><% if score != 10 %></span><% end %>
  <span class="score"><%= score %></span><% if score == 10 %></span><% end %>
</li>

app/views/reviews/_reviews_preview.html.erb
<ol class="reviews">
  <% reviews.each do |r| %>
      <li>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3>
              <strong><%= link_to r.address.formatted_address, r %></strong>
              <small>
                <%= link_to '[Edit]', edit_review_path(r) if r.user_id == current_user.id %>
                <%= link_to '[Delete]', review_path(r), data: { confirm: 'Are you sure?' }, :method => :delete if r.user_id == current_user.id %>
                <span class="pull-right"><%= pluralize(r.descriptions_word_count, 'word') %></span>
              </small>
            </h3>
          </div>
          <div class="panel-body">
            <ul class="scores">
              <%= render partial: 'reviews/review_preview_score', locals: {score: r.building_rating, category: 'Building'} %>
              <%= render partial: 'reviews/review_preview_score', locals: {score: r.furnishings_rating, category: 'Furnishings'} %>
              <%= render partial: 'reviews/review_preview_score', locals: {score: r.noise_rating, category: 'Noise'} %>
              <%= render partial: 'reviews/review_preview_score', locals: {score: r.amenities_rating, category: 'Amenities'} %>
              <%= render partial: 'reviews/review_preview_score', locals: {score: r.transport_rating, category: 'Transport'} %>
            </ul>
          </div>
        </div>
      </li>
  <% end %>
</ol>

app/views/reviews/edit.html.erb
<% provide(:title, 'Edit Your Review') %>

<% content_for :head do %>
    <%= render 'review_js' %>
<% end %>

<div class='container'>
  <h1>Edit Review</h1>

  <%= render 'review_form' %>
</div>

app/views/reviews/new.html.erb
<% provide(:title, 'Write A Review') %>

<% content_for :head do %>
    <%= render 'review_js' %>
<% end %>

<div class='container'>
  <h1>Write A Review</h1>

  <%= render 'review_form' %>
</div>

app/views/reviews/show.html.erb
<% provide(:title, "Review of #{@review.address.formatted_address}") %>

<% content_for :head do %>
    <%= render 'review_js' %>
<% end %>

<div class='container'>
  <h1>
    Review of <strong><%= @review.address.formatted_address %></strong> by
    <% if @review.user_id == current_user.id %>
        <strong><%= link_to 'You', user_path(@review.user) %></strong>
        <small>
          <%= link_to '[Edit]', edit_review_path(@review) %>
          <%= link_to '[Delete]', review_path(@review), data: { confirm: 'Are you sure?' }, :method => :delete %>
        </small>
    <% else %>
        <strong><%= link_to @review.user.name, user_path(@review.user) %></strong>
    <% end %>
  </h1>

  <%= render 'review_form' %>
</div>