config/routes.rb
SampleApp::Application.routes.draw do

  devise_for :users,
             :path => '',
             :path_names => {:sign_in => 'sign-in',
                             :sign_out => 'sign-out',
                             :registration => 'account',
                             :edit => 'edit' },
             :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                               :registrations => "users/registrations" }

  root 'static#home'

  get '/account', to: 'users#show', as: 'account'

  resources :reviews, only: [:new, :create, :update, :show, :edit, :destroy]
  resources :users, only: [:show, :index]

  

end

app/views/layouts/_footer.html.erb
<div class="container">
  <hr>
  <footer>
    <p>&copy; RatedRentals 2013</p>
  </footer>
</div>

app/views/layouts/_login.html.erb
<ul class="nav">
  <% if user_signed_in? %>
      <li>
        <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
      </li>
  <% else %>
      <li>
        <%= link_to 'Login', new_user_session_path %>
      </li>
      <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
  <% end %>
  <% if user_signed_in? %>
      <li>
        <%= link_to 'Edit account', edit_user_registration_path %>
      </li>
  <% else %>
      <li>
        <%= link_to 'Sign up', new_user_registration_path %>
      </li>
  <% end %>
</ul>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
          <%= content_tag :div, msg, :class => flash_class(name) if msg.length > 0 %>
      <% end %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header ">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "RatedRentals", root_path, :class => 'navbar-brand' %>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Rental Reviews</a></li>
      <li><a href="#">Landlord Reviews</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", account_path %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to('Sign out', destroy_user_session_path, :method => :delete) %>
              </li>
            </ul>
          </li>
      <% else %>
          <li>
            <%= link_to "Sign In", new_user_session_path, :class => 'btn btn-default btn-nav' %>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= page_title(yield(:title)) %></title>
  <meta name="description" content="Rails Bootstrap">
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBMTfCaWUIjhrL59z1kL3_sItMtxnl7g5Q&sensor=false&libraries=places" %>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<div class="container">
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>

  <%= yield %>

  <%= render 'layouts/footer' %>
</div>
</body>
</html>